CC=gcc
CFLAGS=-I.

parallel_min_max : /workspaces/os_lab_2019/lab3/src/utils.o /workspaces/os_lab_2019/lab3/src/find_min_max.o /workspaces/os_lab_2019/lab3/src/utils.h /workspaces/os_lab_2019/lab3/src/find_min_max.h 
	$(CC) -o parallel_min_max /workspaces/os_lab_2019/lab3/src/utils.o /workspaces/os_lab_2019/lab3/src/find_min_max.o /workspaces/os_lab_2019/lab3/src/parallel_min_max.c $(CFLAGS)

process_memory : 
	$(CC) -o process_memory process_memory.c $(CFLAGS)
